### ISSUE TITLE
关于选择板块问题

### ISSUE THREAD

**Issue by Rain021300** [F-19-F/XM_BBS#1]
作者您好，我在源代码里找到了选择板块的api，请问我该怎么修改此api，使程序在我指定的板块里进行划水呢？

**Comment by F-19-F** [comment]
内测板块需要权限才能访问相关帖子，所以呢，默认没有通过指定板块来获取帖子，而是获取推荐的帖子。
如果你想用这个api，需要boardId参数，我注释那行（123）boardId是开发版公测的，如果你想在开发版里水，把123行那个#删掉就可以了，其他的板块，修改boardId为对应板块即可。

**Comment by weizuo0408** [comment]
> 内测这个帖子需要获取相关权限，所以呢，默认没有通过指定推荐来获取帖子，可以获取的帖子。
> 如果你使用api，需要boardId参数，我注释那行（123）boardId是开发版公测版的，如果你想在开发里水版，把123行那个人#掉就可以了，其他的欢迎，修改版的我回复了智能手机版。

大佬 你好 我只会使用你的这个程序，前面不太明白 一天运行好三-四次 早上9-10点 下午3-4点  晚上10-11点 凌晨2-3点  已经两次 3天禁言套餐了 哈哈，我自带比较多的内测版，只是618换了新手机没办法入内测，所以想要尽快刷到900分钟，每一天一般运行几次呀？有没有推荐使用方法 不容易被制裁的啊？

**Comment by F-19-F** [comment]
我一般只给热门的前200回复，后面的就不回复，只对帖子和评论点赞。我自己也被禁言过😂，那种不怎么热门的帖子的回复很容易被禁言

**Comment by Rain021300** [comment]
> > 内测这个帖子需要获取相关权限，所以呢，默认没有通过指定推荐来获取帖子，可以获取的帖子。
> > 如果你使用api，需要boardId参数，我注释那行（123）boardId是开发版公测版的，如果你想在开发里水版，把123行那个人#掉就可以了，其他的欢迎，修改版的我回复了智能手机版。
> 
> 大佬你好一天我用的程序，前面-三不太懂你的这个运行好-四次早上910点下午3点-4点晚上10点-11点凌晨2点-3点已经完全3天禁了言语套餐了哈哈，我自带比较多的内测版，只是618换了新没办法入内测，所以手机能很快刷到900分钟，每次一般都会有多少呀？有没有推荐使用方法不容易被自己的啊？

**Comment by Rain021300** [comment]
> 内测这个帖子需要获得相关权限，所以呢，默认没有通过指定推荐来获取帖子，可以获取的帖子。
> 如果你使用api，需要boardId参数，我注释那行（123）boardId是开发版公测版的，如果你想在开发里水，把123行那个#掉下去就可以了，其他的同意，修改版的我回复了智能手机版。

我使用下边那个api代码，脚本会报错哎

**Comment by F-19-F** [comment]
> > 内测这个帖子需要获得相关权限，所以呢，默认没有通过指定推荐来获取帖子，可以获取的帖子。
> > 如果你使用api，需要boardId参数，我注释那行（123）boardId是开发版公测版的，如果你想在开发里水，把123行那个#掉下去就可以了，其他的同意，修改版的我回复了智能手机版。
> 
> 我使用下边那个api代码，脚本会报错哎

等下更新下吧

**Comment by Rain021300** [comment]
> > > 内测这个帖子需要获得相关权限，所以呢，默认没有通过指定推荐来获取帖子，可以获取的帖子。
> > > 如果你使用api，需要boardId参数，我注释那行（123）boardId是开发版公测版的，如果你想在开发里水，把123行那个#掉下去就可以了，其他的同意，修改版的我回复了智能手机版。
> > 
> > 
> > 我使用下边那个api代码，脚本会报错哎
> 
> 等下更新下吧

希望可以加入点赞后间隔时间功能，不然挂机一会儿就点赞过多稍后重试了

**Comment by F-19-F** [comment]
> > > > 内测这个帖子需要获得相关权限，所以呢，默认没有通过指定推荐来获取帖子，可以获取的帖子。
> > > > 如果你使用api，需要boardId参数，我注释那行（123）boardId是开发版公测版的，如果你想在开发里水，把123行那个#掉下去就可以了，其他的同意，修改版的我回复了智能手机版。
> > > 
> > > 
> > > 我使用下边那个api代码，脚本会报错哎
> > 
> > 
> > 等下更新下吧
> 
> 希望可以加入点赞后间隔时间功能，不然挂机一会儿就点赞过多稍后重试了

一个小时对帖子点赞次数限制在100,不是脚本没sleep的问题。。。，对评论点赞没有限制
