### ISSUE TITLE
复制了cookie 运行不了

### ISSUE THREAD

**Issue by ZeYuYang1024** [F-19-F/XM_BBS#10]
![image](https://user-images.githubusercontent.com/24284910/127760217-f35a61aa-15ab-43be-bd13-fa05797c2796.png)

**Comment by F-19-F** [comment]
自己操作问题。
![image](https://user-images.githubusercontent.com/58457605/127760383-d9dad077-a1d9-4807-a4f1-466e3a7bbe0f.png)
