### ISSUE TITLE
我打印了cookie和Client 都没有问题啊

### ISSUE THREAD

**Issue by ZeYuYang1024** [F-19-F/XM_BBS#11]
![image](https://user-images.githubusercontent.com/24284910/127760496-a96c069b-c96e-468a-bc83-da76a6b3e43d.png)

**Comment by F-19-F** [comment]
网络代理关掉再运行。。。。。。。。。。。。。

**Comment by ZeYuYang1024** [comment]
关掉代理就行了，谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: F-19-F ***@***.***&gt;
发送时间: 2021年8月1日 13:42
收件人: F-19-F/XM_BBS ***@***.***&gt;
抄送: yzy-1995 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[F-19-F/XM_BBS] 我打印了cookie和Client 都没有问题啊 (#11)





 
Closed #11.
