### ISSUE TITLE
是不是可以试着加一个延时的功能

### ISSUE THREAD

**Issue by ysxk** [F-19-F/XM_BBS#2]
被封禁了三天哈哈

**Comment by F-19-F** [comment]
被封大概率是复制回复的内容存在问题，代码中本身就设置了延时

**Comment by ysxk** [comment]
> 被封大声明是复制回复的内容问题，代码中就设置好了

怎么关掉这个功能，编辑源码中的哪一行内容

**Comment by F-19-F** [comment]
把201，202，203这三行删掉就可以了

**Comment by ysxk** [comment]
> 把201，202，203这三行放弃就可以了

了解，那我直接注释掉了
