### ISSUE TITLE
使用更新后的脚本报错

### ISSUE THREAD

**Issue by Rain021300** [F-19-F/XM_BBS#3]
如图所示
![微信截图_20210718214441](https://user-images.githubusercontent.com/40193394/126069708-66ea3d24-a481-4a7c-b932-dbb758a4d407.png)

**Comment by Rain021300** [comment]
关闭了自动复制热评，板块为万象息屏。还有个小问题，在别的板块使用脚本时，默认点赞完置顶帖子后，脚本就会卡住没有动作，是我本机的网不好吗.......

**Comment by F-19-F** [comment]
> 关闭了自动复制热评，板块为万象息屏。还有个小问题，在别的板块使用脚本时，默认点赞完置顶帖子后，脚本就会卡住没有动作，是我本机的网不好吗.......

这个....，100%发生吗？

**Comment by Rain021300** [comment]
> 
> 
> > 关闭了自动复制热评，板块为万象息屏。还有个小问题，在别的板块使用脚本时，默认点赞完置顶帖子后，脚本就会卡住没有动作，是我本机的网不好吗.......
> 
> 这个....，100%发生吗？

对的，百分百发生.....

**Comment by F-19-F** [comment]
已经修复
