### ISSUE TITLE
lastest好像无效啊...

### ISSUE THREAD

**Issue by hnuhxt** [F-19-F/XM_BBS#4]
lastest和hot加载出来的帖子是一样的呀

**Comment by F-19-F** [comment]
你确定改的是Autolike函数的参数？指定板块目前没有适配hot和latest

**Comment by hnuhxt** [comment]
对，autolike里面更改前后读取的社区帖子没有变化

**Comment by hnuhxt** [comment]
> 你确定改的是Autolike函数的参数？指定板块目前没有适配hot和latest

对，autolike里面更改前后读取的社区帖子没有变化

**Comment by F-19-F** [comment]
测试没问题，板块指定本来就没有最新和最热选项。
