### ISSUE TITLE
能不能加一个运行多久之后定时关闭啊？

### ISSUE THREAD

**Issue by MichaelthA** [F-19-F/XM_BBS#7]
如题

**Comment by F-19-F** [comment]
一般你跑个100次就被限制点赞次数了。没必要。

**Comment by MichaelthA** [comment]
> 一般你跑个100次就被限制点赞次数了。没必要。

主要是我想挂在群晖每天定时自动，不去人工干预会不会出问题

**Comment by F-19-F** [comment]
> > 一般你跑个100次就被限制点赞次数了。没必要。
> 
> 主要是我想挂在群晖每天定时自动，不去人工干预会不会出问题

cookie有效期没那么长的
