### ISSUE TITLE
个人建议，还是不要用自动回复

### ISSUE THREAD

**Issue by 718986984** [F-19-F/XM_BBS#8]
血泪的教训，点赞就好，回复还是自己动动手吧，我已经被禁言三天了😄

**Comment by F-19-F** [comment]
就算被禁言，那些回复的点赞也可以给你水内测分😏，要刷的快，回复还是要打开的

**Comment by weizuo0408** [comment]
> 就算被禁言，那些回复的点赞也可以给你水内测分😏，要刷的快，回复还是要打开的

啊哈哈  昨天又赠送了 一个7天套餐...前面 已经两次 3天套餐了 我不后悔！ 目前 看有550分了...坐等7.28号 更新分700-800！然后再刷一个星期就行了
