### ISSUE TITLE
在使用SSR全局代理后，无法正常使用

### ISSUE THREAD

**Issue by cr-zhichen** [F-19-F/XM_BBS#9]
在使用SSR全局代理后，无法正常使用  

![报错信息](https://tc.chengrui.xyz/2021/07/27/Code_3ZumrocSHy.png)  

希望能在非Debug运行中增加对其的提示  

![错误提示](https://tc.chengrui.xyz/2021/07/27/Code_LYVg0A07QA.png)  

或者修正这个bug

**Comment by F-19-F** [comment]
em....，这种问题实际不是代码该解决的🌚 挂着代理进不了小米社区app，app只会提示网络异常，而不会告诉你要关闭代理。

**Comment by cr-zhichen** [comment]
emmm 我一开始运行的时候由于用了全局代理，就导致运行就报错，我进入Debug模式运行后才发现是代理的问题，所以还是希望能在README中稍微提醒一下比较好吧
